#!/bin/bash
set -e

echo "Building NoanOS with Initrd Support..."

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( dirname "$SCRIPT_DIR" )"

# Compile kernel and initrd
make -C "$SCRIPT_DIR/boot" clean
make -C "$SCRIPT_DIR/boot" -j4

# Path to the initrd.bin generated by make
INITRD_SRC="$SCRIPT_DIR/boot/bin/initrd.bin"

# Verify initrd.bin existence and size
if [ ! -f "$INITRD_SRC" ]; then
    echo "Error: initrd.bin not found at $INITRD_SRC!"
    exit 1
fi

INITRD_SIZE=$(stat -c%s "$INITRD_SRC")
echo "Initrd size: $INITRD_SIZE bytes"

# Verify initrd.bin > 50KB before building image
if [ $INITRD_SIZE -lt 51200 ]; then
    echo "Warning: initrd.bin is less than 50KB ($INITRD_SIZE bytes)."
fi

# Copy build artifacts to top-level bin directory
mkdir -p "$ROOT_DIR/bin"
cp "$SCRIPT_DIR/boot/bin/boot.bin" "$ROOT_DIR/bin/"
cp "$SCRIPT_DIR/boot/bin/kernel.bin" "$ROOT_DIR/bin/"
cp "$SCRIPT_DIR/boot/bin/initrd.bin" "$ROOT_DIR/bin/"
cp "$SCRIPT_DIR/boot/bin/disk.img" "$ROOT_DIR/bin/"
cp "$SCRIPT_DIR/boot/bin/hdd.img" "$ROOT_DIR/bin/"

echo "Disk image built successfully: $ROOT_DIR/bin/disk.img"

# Optional: run in qemu
if [[ "$1" == "run" ]]; then
    make -C "$SCRIPT_DIR/boot" run -j4
fi
